### ISSUE TITLE
Fill in missing type.

### ISSUE THREAD

**Issue by AnthonyJacob** [dramforever/vscode-ghc-simple#10]
It would be nice, if you add a command to fill in missing type annotations for top level definition.

**Comment by mbwgh** [comment]
Why did you close this? Is this supported already or is this a duplicate? Type insertion would be very useful to have.

**Comment by dramforever** [comment]
@mbwgh duplicate of #11

If you want this feature, check out [Haskutil](https://github.com/EduardSergeev/vscode-haskutil#user-content-fill-typed-hole) which works with this extension and probably does what you want.

**Comment by mbwgh** [comment]
Indeed, a nice, minimal extension. Thanks!
