### ISSUE TITLE
Space in file path causes breakage

### ISSUE THREAD

**Issue by samhopp** [dramforever/vscode-ghc-simple#14]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.10
- Version of VSCode: 1.29.0 (macOS)
- Version of Haskell-related tools:
    
    - GHC: 8.4.4
    - Stack: 1.9.1
    - Cabal:

## Steps to reproduce

1. Create .hs file in any directory so that the file path (file name or any directory in the path) contains at least one space. For example: "~/my haskell files/example file.hs"
2. Open the file in VS Code and write any Haskell code in it.

A space in the file path breaks GHC Simple. As a result none of the GHC Simple features work when editing such file.

**Comment by dramforever** [comment]
Hi! Sorry for the huge delay in updating. The bug you've revealed is now fixed in the latest version of vscode-ghc-simple. If it doesn't work as expected or causes other issues, feel free to reopen this discussion or create a new issue. Anyway, thanks for all your suggestions.
