### ISSUE TITLE
How can I run `cabal repl myCustomTarget`?

### ISSUE THREAD

**Issue by ice1000** [dramforever/vscode-ghc-simple#15]
I didn't see such config. I've set my configs in this way:
![image](https://user-images.githubusercontent.com/16398479/48590971-ad88b900-e90f-11e8-95ba-440a0c8b571d.png)

But I can't see any code insight in my prjo

**Comment by ice1000** [comment]
proj*

**Comment by ice1000** [comment]
dram dram help me

**Comment by dramforever** [comment]
You can't

See #3

**Comment by ice1000** [comment]
Wat if I just need one target, like I have a target with all other targets as dependency. Can I specify that explicitly?

**Comment by ice1000** [comment]
dram dram so cute

**Comment by dramforever** [comment]
We're going to need to generalize [`session.ts`](https://github.com/dramforever/vscode-ghc-simple/blob/master/src/session.ts#L24) here to support this configuration option.

**Comment by ice1000** [comment]
Can dram do that

**Comment by ice1000** [comment]
Thx for the information tho. I modified the installed plugin, added my target directly to `return ['cabal', 'repl']`, but that does not seem to make this plugin work.

**Comment by dramforever** [comment]
`v0.1.11` now allows customizing the REPL command with `ghcSimple.replCommand` and `ghcSimple.replScope`. If this version does not solve this problem or causes other problems, please feel free to reopen this issue or raise a new one.
