### ISSUE TITLE
only one file can take effect in my small project

### ISSUE THREAD

**Issue by zhaohansprt** [dramforever/vscode-ghc-simple#17]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.10
- Version of VSCode: 1.30
- Version of Haskell-related tools:
    
    - GHC: 8.6.2
    - Stack: 1.9.3
    - Cabal:2.2.0.1

## Steps to reproduce

i have 3 executables(appx\main.hs) , 1 src\lib.hs  in my project   and   only the first main.hs  file can take effects of the  vscode-ghc-simple

**Comment by dramforever** [comment]
Try reproducing the problem, and then open the bottom panel with 'problems' 'output' etc and go to the 'output' tab and go to 'GHC' from the dropdown on the right. Paste any output you see there. (If you don't see 'GHC' tell me that as well.)

**Comment by zhaohansprt** [comment]
sorry the missing ,I checked that at the first time i found the problem ; There is no response at all at the invaild file

**Comment by templateK** [comment]
I assume your project is  stack based one.

As far as I know, stack repl tries to load all of the modules of the all targets by default when project target is omitted. so this module conflict message comes out.

To solve this problem,  there must be mechanism to be able to identify project target of the current file, manage different repl sessions for each target and match files and the sessions in this extension.

**Comment by dramforever** [comment]
Sorry for the extremely delayed response. I've recently started working on supporting multi-component/multi-package projects. I think your issue might be helped by this.

Specifically, this way the different executable targets should be isolated into different sessions as templateK mentioned.

If you haven't abandoned vscode-ghc-simple, please consider testing out development versions of the `vgs-bios` branch. See more information in the discussion here: <https://github.com/dramforever/vscode-ghc-simple/discussions/87>.

In short, you will need to install a development version of the `vgs-bios` branch and set up an `hie.yaml` file, with the same format as the one accepted by [hie-bios] to tell vscode-ghc-simple about your project structure. If you need help or find any problems please do consider reaching out.

[hie-bios]: https://github.com/mpickering/hie-bios#explicit-configuration

Not everything is well-supported yet, but hopefully simple multi-component or multi-package setups will work. The same file should also help out those who use ghcide. Many projects already have an `hie.yaml` file, so these will hopefully work out of the box. See the discussion page linked above for details for more information.

Thanks for considering helping out!

**Comment by dramforever** [comment]
Released in v0.2.0
