### ISSUE TITLE
Error highlighting

### ISSUE THREAD

**Issue by DoctorRyner** [dramforever/vscode-ghc-simple#19]
Is there a way to disable error highlighting? I use ghcid instead but want this plugin's other features

**Comment by dramforever** [comment]
Hi! Sorry for the huge delay in updating. Finally, the feature you've requested is now in the latest version of vscode-ghc-simple. If it doesn't work as expected or causes other issues, feel free to reopen this discussion or create a new issue. Anyway, thanks for all your suggestions.

**Comment by DoctorRyner** [comment]
Thanks! That works and that's awesome
