### ISSUE TITLE
Files/folders in project directory displayed as suggestions

### ISSUE THREAD

**Issue by runeksvendsen** [dramforever/vscode-ghc-simple#20]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: `0.0.10`
- Version of VSCode: `1.31.0`
- Version of Haskell-related tools:
    
    - GHC: `8.4.3`
    - Stack: `1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1`
    - Cabal:

## Steps to reproduce

1. Place cursor to the right of the `::` in the following definition:

<img width="790" alt="screenshot 2019-02-09 at 11 09 25" src="https://user-images.githubusercontent.com/1069247/52519456-d1804000-2c5b-11e9-9549-4298b8bd4de0.png">

2. Press space

Expected: reasonable suggestions

Actual: files from the project directory root

## Workspace

Relevant code is here: https://github.com/runeksvendsen/order-graph/blob/765a1679495fdd586321fc67fadd2c2b657127a7/src/OrderBook/Graph/Exchange.hs#L127

**Comment by dramforever** [comment]
Hi! Sorry for the huge delay in updating. The bug you've revealed is now in the latest version of vscode-ghc-simple. If it doesn't work as expected or causes other issues, feel free to reopen this discussion or create a new issue. Anyway, thanks for all your suggestions.
