### ISSUE TITLE
GHCi does not have :loc-at command

### ISSUE THREAD

**Issue by jrodriguesimg** [dramforever/vscode-ghc-simple#21]
- Version of vscode-ghc-simple: v0.0.8
- Version of Haskell-related tools:
    
    - GHCi: 8.6.3
    - Stack: 1.9.3

Hi. I'm just trying to understand how this extension Interacts with GHCI. In `definitions.ts` is suposed the following command run in ghci? The ghci I'm using does not have that command.

```
const cmd = `:loc-at ${document.uri.fsPath} ${1 + + range.start.line} ${1 + + range.start.character} ${1 + + range.end.line} ${1 + + range.end.character} ${document.getText(range)}`;
```

Thanks in advance.

**Comment by jrodriguesimg** [comment]
Sorry. My bad. It has that command. I just can't find documentation for it.

**Comment by dramforever** [comment]
Yeah I was sort of wondering why there isn't `:loc-at`. Glad you figured it out.

It's here, in case anyone else is wondering: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/ghci.html#ghci-cmd-:loc-at
