### ISSUE TITLE
Support for multi-root workspaces?

### ISSUE THREAD

**Issue by afcowie** [dramforever/vscode-ghc-simple#22]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.10
- Version of VSCode: 1.31.1
- Version of Haskell-related tools: GHC 8.6.4, stack 1.9.3

## Workspace

Well, that's the problem. VSCode supports workspaces with multiple repositories (ie, multiple source projects) checked out in them. Which is _awesome_ when you're hacking simultaneously on a library and an application. HIE figures this out, somehow (if I understood correctly they're starting an independent hie-wrapper process for each root!) but Simple didn't have any idea what to do with the folders that were in the workspace after the first one and so spewed GHC package not found errors.

**Comment by afcowie** [comment]
I checked, and dropping to a single root in a workspace does indeed make Simple work fine. So the steps to recreate this are to _add_ a second root (ie, some code that depends on the first) to an existing workspace with `File -> Add Folder to Workspace...` then on reload you'll see one or the other package freaking out.

**Comment by dramforever** [comment]
Hi! Sorry for the huge delay in updating. The feature you've requested is now in the latest version of vscode-ghc-simple. If it doesn't work as expected or causes other issues, feel free to reopen this discussion or create a new issue. Anyway, thanks for all your suggestions.

**Comment by afcowie** [comment]
That's not a small patch. Amazing, thanks!

I'll try and figure out how to build Simple from source over the weekend and give it a test for you.

**Comment by dramforever** [comment]
Thanks for confirming.

> I'll try and figure out how to build Simple from source over the weekend and give it a test for you.

This time you don't need to, because it's already released. Just update from the marketplace (i.e. the 'extensions' tab).

**Comment by afcowie** [comment]
@dramforever installed fine and appears to be working. Thanks!

One thing that made me squint was an error in one file didn't seem to cause a rocochet cascade of errors in other files and in sibling projects.

I think that's fine, because the point is you need to fix that error! I'm not sure showing (what would be the errors) elsewhere is even desirable, but I'm faintly worried that I'd miss an error if (say) a function signature had changed in another module (in another root) and I hadn't propagated the fix properly.

**Comment by danwdart** [comment]
I have multiple roots in my workspace, some not containing stack.yaml files at their roots, and containing multiple stack projects. As a result, running this extension causes ghci to be run from the root, not the stack project, making module errors everywhere. Is there an option I could add to say "You know this file? Well, just run it in its own directory, not the root!"?

**Comment by schuelermine** [comment]
Why is this closed?
