### ISSUE TITLE
Extension no longer works with standalone files

### ISSUE THREAD

**Issue by vituscze** [dramforever/vscode-ghc-simple#28]
## Status

- [ ] A workaround is available
- [x] A fix is written
- [x] A fix is released
- [x] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.1.6
- Version of VSCode: 1.32.3
- Version of Haskell-related tools:
    
    - GHC: 8.6.3
    - Stack: 1.9.1
    - Cabal: 2.4.1.0

## Steps to reproduce

Close all folders/workspaces and open a standalone .hs file. No warnings/errors are provided, type information is missing, etc. This used to work in 0.0.10 and earlier.

## Workspace

N/A

**Comment by dramforever** [comment]
> Close all folders/workspaces

That's one case I haven't considered. Thanks for bringing this up!

**Comment by dramforever** [comment]
Fixed in v0.1.7. If this does not solve this or causes other problems, feel free to reopen this or create a new issue.

**Comment by vituscze** [comment]
Thank you, it works fine now.
