### ISSUE TITLE
VS Code update 1.33 (March 2019) breaks extension

### ISSUE THREAD

**Issue by jannikbuhr** [dramforever/vscode-ghc-simple#31]
## Status

The latest update of VSCode (1.33) seems to have broken the extension. No types are shown and
using the command "Restart GHCi session" results in the error-message:

_command 'vscode-ghc-simple.restart' not found_

- [x] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

As a workaround, you can set the update mode of code in the settings to either "none" or "manual" and continue working on version 1.32.

---

- Version of vscode-ghc-simple: 0.17
- Version of VSCode: 1.33
- Version of Haskell-related tools:
    - GHCi: 8.4.4
    - Stack: 1.10.0
    - lts-12.22

## Steps to reproduce

Update VSCode to version 1.33, open a regular *.hs file

**Comment by ivxvm** [comment]
Confirming the same. Wondering if there is a way to get back older version after update.

**Comment by dramforever** [comment]
Problem is most likely JustusAdam/language-haskell#84, which is also affecting other extensions such as: alanz/vscode-hie-server#148

**Comment by dramforever** [comment]
Fixed upstream. You can update `justusadam.language-haskell` to newest version (2.6.0) and everything should work fine.
