### ISSUE TITLE
Specify target with new-repl

### ISSUE THREAD

**Issue by cah6** [dramforever/vscode-ghc-simple#33]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.1.10
- Version of VSCode: 1.33.1
- Version of Haskell-related tools:
    - GHC: 8.4.3
    - Cabal: 2.2.0.0

## Steps to reproduce

Given the workspace, launch VSCode in the nix shell with `nix-shell -A shells.ghc --run "code ."`. 

I found that you can force cabal new-style commands by setting "workspaceType" to "cabal new", but this doesn't work out of the box with multi-folder repositories. Notably, for these repositories the command needs to be `cabal new-repl all`. Is there a way to specify more arguments that will be passed through to the cabal launch? 

Note that to work around this you can just set workspaceType to "cabal" to use `cabal repl` instead, but I would like to try getting the new-style commands to work.

## Workspace

Workspace available here https://github.com/cah6/haskell-nix-skeleton-2, see .vscode/settings.json for my overrides.

**Comment by edmundnoble** [comment]
Hi there,

You're in luck; I wrote this up just yesterday before seeing your issue! See #34

**Comment by cah6** [comment]
Nice! That looks like exactly what I needed.

**Comment by dramforever** [comment]
I have to say I'm not familiar with how `cabal` works, especially the new-build part.

Is `cabal new-repl all` supposed to *always* select all targets? If so I'm going to actually make that the default, since it's actually what I do for stack.

**Comment by cah6** [comment]
@dramforever I think so! There might be some edge case I don't know about, but it looks like it selects all for single cabal file projects (where the cabal file is in the root, no `.project` file), and multiple cabal file repositories, where the `.project` file points to multiple sub-directories.

**Comment by dramforever** [comment]
`v0.1.11` now uses target `all` by default (`cabal {new,v2}-repl all`) and allows customizing the REPL command with `ghcSimple.replCommand` and `ghcSimple.replScope`. If this version does not solve this problem or causes other problems, please feel free to reopen this issue or raise a new one.
