### ISSUE TITLE
Hardcoded defaults

### ISSUE THREAD

**Issue by llelf** [dramforever/vscode-ghc-simple#4]
1. There's currently no way to specify the project type [stack/cabal/…], is there?
2. Also setting `:set -Wall` is not helpful at all (it overrides all other `-W…`).

**Comment by dramforever** [comment]
Thanks for helping by using the extension and providing feedback!

I agree that this extension would benefit from more configuration options, and I will look into those.

---

**Braindump ahead**

1. Probably a `.vscode/` workspace-local option would do the trick. Currently this is how we decide the project type, in this order. [You can see the code here.](https://github.com/dramforever/vscode-ghc-simple/blob/1a3fc05d0d116aefc2051141807ec6bc672b0874/src/extension-state.ts#L53)
    1. `stack.yaml -> stack repl`, `stack` in code
    2. `*.cabal -> cabal repl`, `cabal`
    3. `stack working -> stack exec ghci`, `bare-stack`
    4. `ghci`, `bare`

    The workspace types differ in how GHCi is started and whether a single session of GHCi is shared (since as you know, `stack repl` takes forever on the 'build' part).
2. Maybe there should be two sets of default options, the 'essential ones' like `-ferror-spans` and the 'helping' ones like `-Wall`. The 'helping' ones will not take effect with 'heavyweight' workspace types, `stack` and `cabal`. Or maybe just make everything configurable?

**Comment by dramforever** [comment]
I've added some configuration options. In short, the workspace type is now configurable, and we no longer `:set -Wall` for 'bare' workspaces.

It's not released yet. You can try out the newest changes by [downloading `.vsix` files from CircleCI](https://circleci.com/gh/dramforever/vscode-ghc-simple/8#artifacts/containers/0). What do you think of it?

**Comment by dramforever** [comment]
Released as `v0.0.9`. Check your 'Extensions' view.
