### ISSUE TITLE
0.1.11 Diagnostics & definition stop working

### ISSUE THREAD

**Issue by Jostar1024** [dramforever/vscode-ghc-simple#40]
## Status

- [x] A workaround is available
use previous version, 0.1.10
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.1.11
- Version of VSCode: 1.36
- Version of Haskell-related tools:
    
    - GHC: 8.6.4
    - Stack: 1.9.3
    - Cabal:

## Steps to reproduce
Install 0.1.11 and put the cursor in front of the variable, normally it shows the definition at the end, while in the newest version it doesn't

## Workspace

I'll create the minimum project later.

**Comment by dramforever** [comment]
I'm dumb, it's most likely this:

https://github.com/dramforever/vscode-ghc-simple/commit/32683c2fe8048cc8c1c360b31a8ebe42da2c6185#diff-f3fe9c4fe673e665c8df5914c3b9c9a0R35

`--colors never` should be `--color never` :man_facepalming:

**Comment by Jostar1024** [comment]
No, you're not. I enjoy this plugin and it helps me A LOT to learn haskell.:)

**Comment by dramforever** [comment]
Thanks for the compliment. Hopefully I fixed it in v0.1.12. If it's not fixed or causes other problems feel free to reopen or create a new issue.
