### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by eo1989** [dramforever/vscode-ghc-simple#46]
- Issue Type: `Bug`
- Extension Name: `vscode-ghc-simple`
- Extension Version: `0.1.13`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by dramforever** [comment]
Not sure what you're getting at there... Where's the bug? Things got messed up when writing?

**Comment by dramforever** [comment]
Closing this. If you're sure you have a problem, reply **with details** in the corresponding issue if it's already been reported, or post a new issue/reopen this one **with details**.
