### ISSUE TITLE
UI indication for long-running process

### ISSUE THREAD

**Issue by EduardSergeev** [dramforever/vscode-ghc-simple#55]
If user opens a (stack) project which has not been built yet it may take a while for stack to download GHC and while it is doing it there is no indication for user what is going on (unless user opens `Output` -> `GHC` tab). The extension's function are just not available while stack prepares the project which can be confusing for a new user.

Is it possible to add some sort of indication, for example in VSCode status bar, notifying user that the extension is "alive but busy"? Progress bar would be even better (but probably also harder to implement).

**Comment by dramforever** [comment]
Implemented in v0.1.19.
