### ISSUE TITLE
Support for cabal new-* family of commands (cabal-only project, no stack)

### ISSUE THREAD

**Issue by oscarvarto** [dramforever/vscode-ghc-simple#6]
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed version is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.9
- Version of VSCode: 1.26.1
- Version of Haskell-related tools:
    
    - GHC: 8.4.3
    - Stack: NONE
    - Cabal: 2.2.0.0

I am working on Windows 10. I have tried stack on Windows 10, but I want to be able to work with cabal only projects (also).

## Steps to reproduce

Start a new haskell project with `cabal init`. Build it using `cabal new-build` Then vscode-ghc-simple extension will start failing.

Follow the steps in the cabal tutorial here: https://haskell-at-work.com/episodes/2018-05-13-introduction-to-cabal.html
Extension will fail to work just after adding `titlecase` dependency to greeter.cabal, and a red squiggle line will show up at import declaration:
`import Data.Text.Titlecase`
with the error message: 
> Could not find module `Data.Text.Titlecase' Use -v to see a list of the files searched for.

I expected the extension to keep working (for example, being able to see the types on current caret position), but instead, I see false positives errors in my code. 

## Workspace

I created a simple minimal repository here: https://github.com/oscarvarto/vscode-ghc-simple-cabal-only

**Comment by dramforever** [comment]
Reproduced! I'll see what I can do.

**Comment by ice1000** [comment]
what can dram do

**Comment by dramforever** [comment]
I couldn't figure out why `cabal new-repl` was failing when run by NodeJS `process` while it does absolutely fine standalone in terminal. I was stumped on this

**Comment by dramforever** [comment]
Hi! Sorry for the huge delay in updating. The feature you've requested is implemented in #24 and is now in the latest version of vscode-ghc-simple. If it doesn't work as expected or causes other issues, feel free to reopen this discussion or create a new issue. Anyway, thanks for all your suggestions.
