### ISSUE TITLE
Don't write interface files by default

### ISSUE THREAD

**Issue by emlautarom1** [dramforever/vscode-ghc-simple#64]
Currently by default `-fwrite-interface` is enabled. This causes that for every `.hs` file that is loaded independently a `.hi` file is generated. The user cannot disable this feature from the config file.

https://github.com/dramforever/vscode-ghc-simple/blob/0dab4ad6df2edfffd39ba0e723ea1006c81164bf/src/session.ts#L158-L163

For example, I have a `Snippets` folder with some `.hs` files that I load into GHCi. I don't want to clutter the folder with `.o` nor `.hi` files. I can avoid the former ones (use `byte-code`) but not the later ones.

![hi-files](https://user-images.githubusercontent.com/31224949/79604967-751d7980-80c5-11ea-837d-855148f86335.png)

**Comment by dramforever** [comment]
I found that `-fwrite-interface` seems to do nothing, so I just removed it. Until the change is released, I think you can just add `.hi` to excluded files to visually feel better.

**Comment by emlautarom1** [comment]
TIL you can hide `.hi` files. Thanks!
