### ISSUE TITLE
Fails to work with -Werror=missing-home-modules

### ISSUE THREAD

**Issue by LukaHorvat** [dramforever/vscode-ghc-simple#7]
## Status

- [ ] A workaround is available
- [x] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.0.9
- Version of VSCode: 1.27.1
- Version of Haskell-related tools:
    - GHC: 8.2.2
    - Stack: 1.8.0
    - Cabal: 1.24.0.2

## Steps to reproduce

Our project has the following GHC flags enabled: `-Wall -Werror=missing-home-modules`
This means that compilation fails if we forget to put one of our modules into `exposed-modules` or `other-modules` in the cabal file. Apparently these flags get picked up by vscode-ghc-simple, but the `exposed/other-modules` field doesn't because I get this in the logs:

```
ghci | ===ghci_barrier_0.5873931443816673===
    -> :set +c
    |> :load *path-to-file\Model.hs
ghci | 
ghci | <no location info>: warning: [-Wmissing-home-modules]
ghci |     Modules are not listed in command line but needed for compilation: Common
ghci |                                                                        Controller.Common
ghci |                                                                        Elm.TyRep.Generic
ghci |                                                                        Influx
ghci |                                                                        Mail
ghci |                                                                        Servant.Authorization
ghci |                                                                        Settings
ghci |                                                                        Template
ghci |                                                                        WebSockets
ghci | 
ghci | <no location info>: error: 
ghci | Failing due to -Werror.
ghci | Failed, no modules loaded.
ghci | 
ghci | ===ghci_barrier_0.553306963977297===
    -> :show modules
ghci | 
ghci | ===ghci_barrier_0.24731998431225644===
    -> :module 
ghci | 
ghci | ===ghci_barrier_0.18661016316355594===
    -> :all-types
ghci | 
ghci | ===ghci_barrier_0.18404214441411337===
```

Those modules are definitely in the cabal file.

**Comment by LukaHorvat** [comment]
This is after a restart. I didn't edit the cabal file.

**Comment by dramforever** [comment]
Sorry for the huge delay in updating.

I was unable to reproduce this. I'm using more up-to-date versions of tools and trying [the pandoc git repo](https://github.com/jgm/pandoc/tree/6be8f4e953b6ba9a7af1b707ef3902f8a5b7b8e2) which [has `-Werror=missing-home-modules` enabled](https://github.com/jgm/pandoc/blob/6be8f4e953b6ba9a7af1b707ef3902f8a5b7b8e2/pandoc.cabal#L442), and the extension works fine.

Do you have a more specific repository or something that I can take a look at?

**Comment by dramforever** [comment]
I've released a new version that should no longer have this problem. If you think this issue is not fixed or it caused other problems, feel free to reopen this discussion or create a new one.
