### ISSUE TITLE
Best way to handle multiple packages?

### ISSUE THREAD

**Issue by malte-v** [dramforever/vscode-ghc-simple#77]
My VSCode workspace contains three subfolders, each of them is a Haskell package. Is there some way I can configure this to create three GHCi sessions, one for each package, so I can work on them in parallel? Thanks!

**Comment by mustafahafidi** [comment]
This extension can't handle more than one GHCI session. Usually, when I have to deal with multiple packages I open multiple vscode windows

**Comment by dramforever** [comment]
This feature is considered and will be included in an overhaul of the GHCi session system. However I have other things to do. Meanwhile although far from ideal you can work in multiple windows as @mustafahafidi said.

@mustafahafidi Thanks for helping with issues.

**Comment by dramforever** [comment]
Sorry for the extremely delayed response. I've recently started working on supporting multi-component/multi-package projects, which would hopefully fix this issue.

If you haven't abandoned vscode-ghc-simple, please consider testing out development versions of the `vgs-bios` branch. See more information in the discussion here: <https://github.com/dramforever/vscode-ghc-simple/discussions/87>.

In short, you will need to install a development version of the `vgs-bios` branch and set up an `hie.yaml` file, with the same format as the one accepted by [hie-bios] to tell vscode-ghc-simple about your project structure. If you need help or find any problems please do consider reaching out.

[hie-bios]: https://github.com/mpickering/hie-bios#explicit-configuration

Not everything is well-supported yet, but hopefully simple multi-component or multi-package setups will work. The same file should also help out those who use ghcide. Many projects already have an `hie.yaml` file, so these will hopefully work out of the box. See the discussion page linked above for details for more information.

Thanks for considering helping out!

**Comment by dramforever** [comment]
Released in v0.2.0
