### ISSUE TITLE
Completion feature can't be disabled

### ISSUE THREAD

**Issue by kirillFedorov1** [dramforever/vscode-ghc-simple#78]
Could someone please check if completion feature can be disabled. I don't really need it, tried to disable it everywhere in settings, but it continues to work.

**Comment by dramforever** [comment]
I tried both single file and project and it seems to work for me. Does this happen everywhere?

It's possible that a recent VSCode update broke it. I'll take a look.

**Comment by kirillFedorov1** [comment]
@dramforever Yes, it happens both in a single file and in a project for me.

**Comment by dramforever** [comment]
What's your vscode version? Could be that the API changed while I wasn't watching

**Comment by kirillFedorov1** [comment]
@dramforever vscode version is 1.46.1.

**Comment by dramforever** [comment]
I just upgraded to 1.46.1 and disabling completion seems to work. Maybe you're seeing 'word based suggestions'? Those aren't from the extension and you can disable that separately. Maybe you can take a screenshot and I'll see

**Comment by kirillFedorov1** [comment]
@dramforever you are right, it were word-based suggestions. Sorry for the confusion.

**Comment by dramforever** [comment]
Glad you were able to figure it out
