### ISSUE TITLE
<command line>: cannot satisfy -package, target is not a target

### ISSUE THREAD

**Issue by cblp** [dramforever/vscode-ghc-simple#79]
`<command line>: cannot satisfy -package hoppy-runtime` when only non-buildable components depend on it.

Maybe the root of the problem is in Stack because Stack both says:
1. It is a target: Stack lists the non-buildable component in `stack ide targets`.
2. It is not a target: "The following components have 'buildable: False' set in the cabal configuration, and so cannot be targets"

## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed version is on the marketplace.

---

- Version of vscode-ghc-simple: 0.1.22
- Version of VSCode: 1.46.1
- Version of Haskell-related tools:
    
    - GHC: 8.8.3
    - Stack: 2.3.1

## Steps to reproduce

Create a Stack project with a special component:
1. It depends on an unknown package (unknown to Hackage or to the current build config).
2. It is disabled: `buildable: False`

I expect normal operation with other components.

I got `<command line>: cannot satisfy -package hoppy-runtime` and the plugin doesn't work at all.

## Workspace

You can test with https://github.com/ff-notes/ron

## GHC log

https://gist.github.com/cblp/89cdbe6efd1e66bb57540fb736b815ae

**Comment by dramforever** [comment]
Sorry for the extremely delayed response. I've recently started working on supporting multi-component/multi-package projects. I think your issue might be helped by this.

Specifically, this way the different packages will be isolated, and a non-buildable package should not affect files in packages.

If you haven't abandoned vscode-ghc-simple, please consider testing out development versions of the `vgs-bios` branch. See more information here: <https://github.com/dramforever/vscode-ghc-simple/discussions/87>.

In short, you will need to install a development version of the `vgs-bios` branch and set up an `hie.yaml` file, with the same format as the one accepted by [hie-bios] to tell vscode-ghc-simple about your project structure. If you need help or find any problems please do consider reaching out.

[hie-bios]: https://github.com/mpickering/hie-bios#explicit-configuration

Not everything is well-supported yet, but hopefully simple multi-component or multi-package setups will work. The same file should also help out those who use ghcide. Many projects already have an `hie.yaml` file, so these will hopefully work out of the box. See the discussion page linked above for details for more information.

Thanks for considering helping out!

**Comment by cblp** [comment]
I'm not using vscode-ghc-simple, when HLS will fail again, I'll try _simple.

**Comment by dramforever** [comment]
Thanks, appreciate your support

**Comment by dramforever** [comment]
Released in v0.2.0
