### ISSUE TITLE
dependency on 'Haskell Syntax Highlighting' plugin

### ISSUE THREAD

**Issue by 2mol** [dramforever/vscode-ghc-simple#8]
Hi! First of all, thank you very much for writing this plugin, it's really great for simple use cases.

A dependency on [Haskell Syntax Highlighting](https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell) would be very nice to save newcomers a couple of minutes of searching. cf [extensionDependencies](https://code.visualstudio.com/docs/extensionAPI/extension-manifest)

I can make a PR if you want.

**Comment by dramforever** [comment]
Fixed in v0.0.10 (bdbe8180c3865b8724fb5ba2919c9910114667a5). Should be up soon
