### ISSUE TITLE
[Question] How to make documentation for system modules appear?

### ISSUE THREAD

**Issue by Stexxe** [dramforever/vscode-ghc-simple#97]
When I hover over the function it says:
> putStrLn :: String -> IO () 	-- Defined in ‘System.IO’
ghc-9.0.2: Can't find any documentation for System.IO. This is probably because the module was compiled without -haddock, but it's also possible that the module contains no documentation.
Try re-compiling with -haddock.

Could you please tell me how to recompile system modules with `-haddock` (I use stack)? Or maybe I should use an older version of ghc?

**Comment by Stexxe** [comment]
I've fixed it by switching to ghc 8.10.4 (lts-18.6).

**Comment by dramforever** [comment]
This is interesting. Perhaps something had changed between stack's GHC libraries between the two versions.

For the record, I just use the `:doc` command of GHCi and honestly I have no idea how exactly I can get docs for it all the time. It does seem to work with the 'current project' better than dependency libraries.
