### ISSUE TITLE
Diagnostics parsing is broken for GHC versions after 9.6.*

### ISSUE THREAD

**Issue by EduardSergeev** [dramforever/vscode-ghc-simple#98]
## Status

- [ ] A workaround is available
- [x] A fix is written
- [ ] A fix is released
- [ ] The fixed version is on the marketplace.

---

- Version of vscode-ghc-simple: `0.2.3`
- Version of VSCode: 
- Version of Haskell-related tools:
    
    - GHC: `9.6.3`
    - Stack: `2.13.1`
    - Cabal: N/A

## Steps to reproduce

Open Stack project targeting GHC version newer than `9.6.*` (e.g. `9.6.3`) which generates warning (and probably some errors?). Check how these warning are displayed in `PROBLEMS` tab.

When the same project targets GHC versions `6.4.*` or older all warning are correctly parsed and displayed. However warning (and probably some errors?) generated by GHC `9.6.*` are not being parsed by `vscode-ghc-simple`, e.g.:
![image](https://github.com/dramforever/vscode-ghc-simple/assets/722409/34ccc203-d560-4dde-abf2-7cde41c36947)

## Workspace

I believe any Stack project targeting newer version of GHC will have this problem, e.g. [this project's branch](https://github.com/EduardSergeev/monad-memo/tree/demo/ghc-warnings) which [targets GHC 9.6.4](https://github.com/EduardSergeev/monad-memo/blob/7451c5c6f5b2cb0a163336189b220cae86f28b2b/stack.yaml#L1) generates a lot of warnings which cannot be parsed by the latest version of `vscode-ghc-simple`
## GHC log

[vscode-ghc-simple log](https://gist.githubusercontent.com/EduardSergeev/aafea607444518c4d59d422a41574b70/raw/c0eee895d161c7af53ee21fe0043ab5c066f454b/log.txt)

**Comment by Hexadecimaaal** [comment]
closed by #100 and release v0.2.4.
